@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.thenextlvl.npc.api;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;