@MethodsReturnNotNullByDefault
@ParametersAreNotNullByDefault
package net.thenextlvl.npc.api;

import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNotNullByDefault;